export const CORPORATE_PRODUCTS = [
  {
    id: 'team-tshirts',
    name: 'Team T-Shirts',
    catalog: 'corporate',
    price: 599,
    discount: 20,
    tagline: 'Branded basics your team will actually wear.',
    image: 'tshirt',
    material: 'Recycled Cotton-Poly Blend',
    quality: 'Combed Fabric, Screen-Print Ready',
    features: ['Soft Hand-Feel', 'Pre-Shrunk', 'Custom Branding Available'],
    impact: 'Bulk orders are produced from recycled fibre, with your company\'s collection volume tracked on your RePartner dashboard.',
    description: 'A soft, breathable tee built for company-wide rollouts — onboarding kits, town halls, or team days — with space for custom branding.',
  },
  {
    id: 'corporate-uniforms',
    name: 'Corporate Uniforms',
    catalog: 'corporate',
    price: 1399,
    discount: 20,
    tagline: 'Professional uniforms with a lower footprint.',
    image: 'uniform',
    material: 'Recycled Poly-Cotton Twill',
    quality: 'Wrinkle-Resistant Finish',
    features: ['Wrinkle-Resistant', 'Colourfast', 'Tailored Fit Options'],
    impact: 'Front-desk and operations uniforms produced at scale from recycled fibre, reducing your organisation\'s virgin-plastic footwear and apparel footprint.',
    description: 'A polished, wrinkle-resistant uniform set for front-of-house and operations teams, available in tailored fit options and your brand\'s colour palette.',
  },
  {
    id: 'employee-bags',
    name: 'Employee Bags',
    catalog: 'corporate',
    price: 1299,
    discount: 20,
    tagline: 'Onboarding kits that double as everyday carry.',
    image: 'bag',
    material: 'Recycled Ballistic Nylon',
    quality: 'Padded Laptop Sleeve',
    features: ['Padded Laptop Sleeve', 'Water-Resistant', 'Multiple Compartments'],
    impact: 'Each bag\'s shell fibre is sourced from recycled plastic, with bulk orders contributing measurable diversion volume to your sustainability report.',
    description: 'A practical work bag with a padded laptop sleeve and water-resistant shell, ideal for new-hire kits or company-wide gifting.',
  },
  {
    id: 'corporate-hoodies',
    name: 'Hoodies',
    catalog: 'corporate',
    price: 1599,
    discount: 20,
    tagline: 'Premium branded hoodies for hybrid teams.',
    image: 'hoodie',
    material: 'Recycled Polyester Blend',
    quality: 'Premium Heavyweight Fabric',
    features: ['Heavyweight', 'Lined Hood', 'Custom Embroidery Available'],
    impact: 'Heavyweight recycled-polyester hoodies, with embroidery options that keep branding minimal and the fabric the focus.',
    description: 'A premium heavyweight hoodie for hybrid and remote teams, with a lined hood and clean silhouette suited to client-facing wear.',
  },
  {
    id: 'merchandise-kits',
    name: 'Merchandise Kits',
    catalog: 'corporate',
    price: 2199,
    discount: 20,
    tagline: 'A complete branded kit, sustainably sourced.',
    image: 'kit',
    material: 'Mixed Recycled Materials',
    quality: 'Curated Multi-Item Set',
    features: ['Tote + Tee + Bottle Combo', 'Custom Packaging', 'Bulk Pricing Tiers'],
    impact: 'A bundled kit — tote, tee, and a reusable bottle — designed to replace single-use conference and event swag with material that traces back to your ReBin partnership.',
    description: 'A curated merchandise bundle for events, conferences, and client gifting, combining our recycled tote, tee, and a reusable bottle in custom packaging.',
  },
]
