export const PUBLIC_PRODUCTS = [
  {
    id: 'eco-hoodie',
    name: 'Eco Hoodie',
    catalog: 'public',
    price: 1499,
    tagline: 'Heavyweight comfort, made from what we collected.',
    image: 'hoodie',
    material: 'Recycled Polyester Blend',
    quality: 'Premium Heavyweight Fabric',
    features: ['Durable', 'Breathable', 'Comfort Fit'],
    impact: 'Each hoodie is woven from the equivalent of 12 recycled plastic bottles collected through our ReBin network, diverting roughly 0.3kg of plastic from landfill.',
    description: 'Our signature hoodie is built for everyday wear — a heavyweight recycled-polyester blend that holds its shape wash after wash. Cut for a relaxed, comfortable fit with a lined hood and kangaroo pocket.',
  },
  {
    id: 'eco-tshirt',
    name: 'Eco T-Shirt',
    catalog: 'public',
    price: 699,
    tagline: 'A soft daily staple with a circular backstory.',
    image: 'tshirt',
    material: 'Recycled Cotton-Poly Blend',
    quality: 'Soft Combed Fabric',
    features: ['Lightweight', 'Breathable', 'Pre-Shrunk'],
    impact: 'Made from a blend that incorporates recycled fibre from collected plastic, each tee offsets approximately 0.15kg of virgin plastic production.',
    description: 'An everyday tee that doesn\'t compromise on softness. The combed cotton-poly blend is pre-shrunk and breathable, with reinforced seams for a longer wardrobe life.',
  },
  {
    id: 'eco-tote',
    name: 'Eco Tote Bag',
    catalog: 'public',
    price: 349,
    tagline: 'Carry less waste, one bag at a time.',
    image: 'tote',
    material: 'Recycled Canvas',
    quality: 'Reinforced Stitching',
    features: ['Spacious', 'Durable', 'Foldable'],
    impact: 'A single tote replaces hundreds of single-use plastic bags over its lifetime, while its canvas is spun from recycled fibre.',
    description: 'A roomy, foldable canvas tote built to replace single-use bags for good. Reinforced stitching at every stress point means it carries groceries, books, or gear without giving out.',
  },
  {
    id: 'sustainable-shoes',
    name: 'Sustainable Shoes',
    catalog: 'public',
    price: 2999,
    tagline: 'Step lighter — literally and environmentally.',
    image: 'shoes',
    material: 'Ocean-Bound Plastic Knit Upper, Recycled Rubber Sole',
    quality: 'Engineered Knit Construction',
    features: ['Lightweight', 'Breathable', 'Shock-Absorbing'],
    impact: 'Each pair\'s knit upper is made from ocean-bound plastic fibre, while the sole reuses recycled rubber compound, keeping roughly 0.5kg of plastic in circulation rather than the ocean.',
    description: 'A knit sneaker designed for all-day wear. The breathable upper is spun from ocean-bound plastic fibre, paired with a cushioned, shock-absorbing sole made from recycled rubber compound.',
  },
]
