export const REBIN_LOCATIONS = [
  {
    id: 'zoho',
    name: 'Zoho',
    city: 'Chennai',
    kg: 8,
    type: 'Corporate Campus',
    installed: 'April 2026',
    bins: 2,
    note: 'Our highest-collecting site — Zoho\'s campus cafeteria and break-out zones host two ReBins that fill fastest during lunch hours.',
  },
  {
    id: 'srm-institute',
    name: 'SRM Institute',
    city: 'Chennai',
    kg: 7,
    type: 'University',
    installed: 'April 2026',
    bins: 2,
    note: 'Placed across two hostel blocks, student volunteers help log fill levels weekly.',
  },
  {
    id: 'anna-university',
    name: 'Anna University',
    city: 'Chennai',
    kg: 6,
    type: 'University',
    installed: 'April 2026',
    bins: 1,
    note: 'Located near the main library, this ReBin sees steady traffic from students between classes.',
  },
  {
    id: 'loyola-college',
    name: 'Loyola College',
    city: 'Chennai',
    kg: 5,
    type: 'College',
    installed: 'May 2026',
    bins: 1,
    note: 'A student sustainability club adopted this bin and runs a monthly clean-collection drive around it.',
  },
  {
    id: 'mcc',
    name: 'MCC',
    city: 'Chennai',
    kg: 4,
    type: 'College',
    installed: 'May 2026',
    bins: 1,
    note: 'Madras Christian College\'s eco-committee tracks this bin as part of their green campus initiative.',
  },
  {
    id: 'vit-chennai',
    name: 'VIT Chennai',
    city: 'Chennai',
    kg: 5,
    type: 'University',
    installed: 'May 2026',
    bins: 1,
    note: 'Installed near the student activity centre, with peak usage during evening hours.',
  },
  {
    id: 'tidel-park',
    name: 'Tidel Park',
    city: 'Chennai',
    kg: 6,
    type: 'IT Park',
    installed: 'June 2026',
    bins: 1,
    note: 'A shared bin serving multiple tenant companies across the IT park\'s common food court.',
  },
  {
    id: 'kristu-jayanti',
    name: "Kristu Jayanti College",
    city: 'Bengaluru',
    kg: 4,
    type: 'College',
    installed: 'May 2026',
    bins: 1,
    note: 'Our first Bengaluru site, launched in partnership with the college\'s environmental science department.',
  },
  {
    id: 'christ-university',
    name: 'Christ University',
    city: 'Bengaluru',
    kg: 3,
    type: 'University',
    installed: 'May 2026',
    bins: 1,
    note: 'Positioned at the central quad, this bin anchors a growing student recycling pledge programme.',
  },
  {
    id: 'jain-university',
    name: 'Jain University',
    city: 'Bengaluru',
    kg: 3,
    type: 'University',
    installed: 'June 2026',
    bins: 1,
    note: 'One of our newest sites, already on track to match older locations within its first month.',
  },
  {
    id: 'st-josephs-commerce',
    name: "St Joseph's College of Commerce",
    city: 'Bengaluru',
    kg: 4,
    type: 'College',
    installed: 'June 2026',
    bins: 1,
    note: 'Commerce students here are piloting a peer-led tracking sheet to publish weekly collection updates.',
  },
]

export const CITY_TOTALS = REBIN_LOCATIONS.reduce((acc, loc) => {
  acc[loc.city] = (acc[loc.city] || 0) + loc.kg
  return acc
}, {})

export const GRAND_TOTAL_KG = REBIN_LOCATIONS.reduce((sum, l) => sum + l.kg, 0)
export const TOTAL_BINS = REBIN_LOCATIONS.reduce((sum, l) => sum + l.bins, 0)
