export const SCHOOL_PRODUCTS = [
  {
    id: 'school-uniform',
    name: 'School Uniform',
    catalog: 'school',
    price: 1199,
    discount: 15,
    tagline: 'Everyday uniform sets made from recycled fibre.',
    image: 'uniform',
    material: 'Recycled Poly-Cotton Twill',
    quality: 'Reinforced Stitching, Colourfast Dye',
    features: ['Easy-Care Fabric', 'Shrink Resistant', 'Reinforced Knees & Elbows'],
    impact: 'Bulk uniform orders are produced from recycled fibre sourced through our own ReBin collection network, closing the loop within the school community.',
    description: 'A durable, easy-care uniform set designed for daily school wear, woven from a recycled poly-cotton twill that holds colour and shape through repeated washing.',
  },
  {
    id: 'school-shoes',
    name: 'School Shoes',
    catalog: 'school',
    price: 1799,
    discount: 15,
    tagline: 'All-day comfort for the school run.',
    image: 'shoes',
    material: 'Recycled Mesh Upper, Rubber Sole',
    quality: 'Cushioned Insole, Reinforced Toe',
    features: ['Breathable', 'Non-Slip Sole', 'Velcro & Lace Options'],
    impact: 'Uppers are knitted from recycled plastic fibre, diverting collected material from the school\'s own ReBin straight back into student footwear.',
    description: 'Built for the classroom and the playground alike — a breathable recycled-mesh shoe with a non-slip rubber sole and reinforced toe for everyday durability.',
  },
  {
    id: 'house-dress',
    name: 'House Dress',
    catalog: 'school',
    price: 899,
    discount: 15,
    tagline: 'House-colour kits for sports day and beyond.',
    image: 'housedress',
    material: 'Recycled Polyester Pique',
    quality: 'Fade-Resistant Print',
    features: ['Quick-Dry', 'Breathable', 'Fade-Resistant'],
    impact: 'Produced in small batches per house colour to minimise offcut waste, using recycled polyester pique fabric.',
    description: 'A breathable, quick-dry house dress in your school\'s colours, printed with fade-resistant inks so it stays vivid through a full sports season.',
  },
  {
    id: 'sports-jersey',
    name: 'Sports Jersey',
    catalog: 'school',
    price: 949,
    discount: 15,
    tagline: 'Team kits built for movement.',
    image: 'jersey',
    material: 'Recycled Performance Mesh',
    quality: 'Moisture-Wicking Finish',
    features: ['Moisture-Wicking', 'Stretch Fit', 'Breathable Mesh Panels'],
    impact: 'Performance mesh panels are knitted from recycled plastic yarn, giving collected bottles a second life on the sports field.',
    description: 'A stretch-fit jersey with breathable mesh side panels and a moisture-wicking finish, designed to keep up with inter-house matches and practice alike.',
  },
  {
    id: 'school-bag',
    name: 'School Bag',
    catalog: 'school',
    price: 1599,
    discount: 15,
    tagline: 'Sturdy daily carry, lighter on the planet.',
    image: 'bag',
    material: 'Recycled Ballistic Nylon',
    quality: 'Padded Straps, Reinforced Base',
    features: ['Water-Resistant', 'Padded Back Panel', 'Multiple Compartments'],
    impact: 'Each bag\'s ballistic nylon shell is woven from recycled fibre, with offcuts repurposed into smaller accessory pouches.',
    description: 'A water-resistant school bag with a padded back panel and reinforced base, built to handle textbooks and a full school year without sagging.',
  },
]
